BASE_URL = "https://stellarburgers.nomoreparties.site"
LOGIN_URL = f"{BASE_URL}/login"
PROFILE_URL= f"{BASE_URL}/account/profile"
FORGOT_PASSWORD_URL = f"{BASE_URL}/forgot-password"
RESET_PASSWORD = f"{BASE_URL}/reset-password"
ORDER_FEED_URL = f"{BASE_URL}/feed"
USER_REGISTER = f"{BASE_URL}/register"
ORDER_HISTORY_URL = f"{BASE_URL}/account/order-history"
